POST http://localhost:8001/services/hello-world-service/plugins
Content-Type: application/x-www-form-urlencoded

name=jwt&config.secret_is_base64=false&config.key_claim_name=kid&config.claims_to_verify=exp&config.run_on_preflight=true